# Generated by Django 5.1.5 on 2025-01-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieStore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="movie_images/"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Model",
        ),
    ]
